# Default values for helm-app.
# This is a YAML-formatted file. Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: xxxxxxx.dkr.ecr.es-east-1.amazonaws.com/gitops-argocd
  version: main-dab69f2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name:

podSecurityContext: {}

securityContext: {}


service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-app.local
      paths: []
  tls: []


resources: {}

nodeSelector: {}
tolerations: []

affinity: {}
